deployment:
  tasks:
    - export DEPLOYPATH=/home/skillien/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp .gitignore $DEPLOYPATH
    - /bin/cp google8197e8c1d7748239.html $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
